{% set version = '1.0.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-skimr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/skimr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/skimr/skimr_{{ version }}.tar.gz
  sha256: ae76cdbbdb9ba5cd5de8d8ddfc8b1fd97a056eed599298070848c29d7fa2e4f0

build:
  merge_build_host: True  # [win]
  number: 1000
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-cli
    - r-dplyr >=0.7
    - r-knitr >=1.2
    - r-magrittr
    - r-pander
    - r-purrr
    - r-rlang
    - r-stringr >=1.1
    - r-tibble >=0.6
    - r-tidyr >=0.7
    - r-tidyselect >=0.2.4
  run:
    - r-base
    - r-cli
    - r-dplyr >=0.7
    - r-knitr >=1.2
    - r-magrittr
    - r-pander
    - r-purrr
    - r-rlang
    - r-stringr >=1.1
    - r-tibble >=0.6
    - r-tidyr >=0.7
    - r-tidyselect >=0.2.4

test:
  commands:
    - $R -e "library('skimr')"           # [not win]
    - "\"%R%\" -e \"library('skimr')\""  # [win]

about:
  home: https://github.com/ropenscilabs/skimr
  license: GPL-3
  summary: A simple to use summary function that can be used with pipes and displays nicely in
    the console. The default summary statistics may be  modified by the user as can
    the default formatting. Support for data frames  and vectors is included, and users
    can implement their own skim methods for specific object types as described in a
    vignette. Default summaries include support for inline spark graphs. Instructions
    for managing these on  specific operating systems are given in the "Using skimr"
    vignette and the  README.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: skimr
# Title: Compact and Flexible Summaries of Data
# Version: 1.0.4
# Authors@R: c( person("Amelia", "McNamara", email="amcnamara@smith.edu", role = "aut"), person("Eduardo", "Arino de la Rubia", email="earino@gmail.com", role = "aut"), person("Hao", "Zhu", email="haozhu233@gmail.com", role = "aut"), person("Julia", "Lowndes", email="lowndes@nceas.ucsb.edu", role = 'ctb'), person("Shannon", "Ellis", email="sellis18@jhmi.edu", role = "aut"), person("Elin", "Waring", email="elin.waring@gmail.com", role = "cre"), person("Michael", "Quinn", email="msquinn@google.com", role = "aut"), person("Hope", "McLeod", email="hmgit2@gmail.com", role = 'ctb'), person("Hadley", "Wickham", email="hadley@rstudio.com", role = 'ctb'), person("Kirill", "Muller", email="krlmlr+r@mailbox.org", role = 'ctb'), person(family = "RStudio, Inc.", role = "cph", comment = "Spark functions"), person("Connor", "Kirkpatrick", email="hello@connorkirkpatrick.com", role = 'ctb'), person("Scott", "Brenstuhl", email="brenstsr@miamioh.edu", role = 'ctb'), person("Patrick", "Schratz", email="patrick.schratz@gmail.com", role = 'ctb'), person("lbusett", "", email="lbusett@gmail.com", role='ctb'), person("Mikko","Korpela", email="mvkorpel@iki.fi", role='ctb'), person("Jennifer","Thompson", email="thompson.jennifer@gmail.com", role='ctb'), person("Harris","McGehee", email="mcgehee.harris@gmail.com", role='ctb') )
# Description: A simple to use summary function that can be used with pipes and displays nicely in the console. The default summary statistics may be  modified by the user as can the default formatting. Support for data frames  and vectors is included, and users can implement their own skim methods for specific object types as described in a vignette. Default summaries include support for inline spark graphs. Instructions for managing these on  specific operating systems are given in the "Using skimr" vignette and the  README.
# Depends: R (>= 3.1.2)
# Imports: cli, dplyr (>= 0.7), magrittr, pander, purrr, rlang, stats, stringr (>= 1.1), knitr (>= 1.2), tibble (>= 0.6), tidyr (>= 0.7), tidyselect (>= 0.2.4)
# Suggests: extrafont, rmarkdown, testthat (>= 2.0.0), withr, covr
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/ropenscilabs/skimr
# BugReports: https://github.com/ropenscilabs/skimr/issues
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# Collate: 'dplyr.r' 'skimr-package.R' 'formats.R' 'stats.R' 'functions.R' 'kable.R' 'options.R' 'pander.R' 'skim.R' 'skim_print.R' 'skim_v.R' 'summary.R' 'utils.R' 'wide.R'
# NeedsCompilation: no
# Packaged: 2019-01-13 17:23:04 UTC; elinwaring
# Author: Amelia McNamara [aut], Eduardo Arino de la Rubia [aut], Hao Zhu [aut], Julia Lowndes [ctb], Shannon Ellis [aut], Elin Waring [cre], Michael Quinn [aut], Hope McLeod [ctb], Hadley Wickham [ctb], Kirill Muller [ctb], RStudio, Inc. [cph] (Spark functions), Connor Kirkpatrick [ctb], Scott Brenstuhl [ctb], Patrick Schratz [ctb], lbusett [ctb], Mikko Korpela [ctb], Jennifer Thompson [ctb], Harris McGehee [ctb]
# Maintainer: Elin Waring <elin.waring@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-01-13 17:50:03 UTC
