{% set version = '1.0.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-skimr
  version: {{ version|replace("-", "_") }}

source:
  fn: skimr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/skimr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/skimr/skimr_{{ version }}.tar.gz
  sha256: bb082721cc5ef8e90c65f4b31180a77c353352b1b6e8f3eb8dcf70827dfedab0

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-cli
    - r-dplyr >=0.7
    - r-knitr >=1.2
    - r-magrittr
    - r-pander
    - r-purrr
    - r-rlang
    - r-stringr >=1.1
    - r-tibble >=0.6
    - r-tidyr >=0.7
    - r-tidyselect >=0.2.4
  run:
    - r-base
    - r-cli
    - r-dplyr >=0.7
    - r-knitr >=1.2
    - r-magrittr
    - r-pander
    - r-purrr
    - r-rlang
    - r-stringr >=1.1
    - r-tibble >=0.6
    - r-tidyr >=0.7
    - r-tidyselect >=0.2.4

test:
  commands:
    - $R -e "library('skimr')"           # [not win]
    - "\"%R%\" -e \"library('skimr')\""  # [win]

about:
  home: https://github.com/ropenscilabs/skimr
  license: GPL-3
  summary: A simple to use summary function that can be used with pipes and displays nicely in
    the console. The default summary statistics may be  modified by the user as can
    the default formatting. Support for data frames  and vectors is included, and users
    can implement their own skim methods for specific object types as described in a
    vignette. Default summaries include support for inline spark graphs. Instructions
    for managing these on  specific operating systems are given in the "Using skimr"
    vignette and the  README.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
