travis:
  secure:
    BINSTAR_TOKEN: kViQYfM4wKobdr5pDilTgUIxzSSqBQd1fWVsq6NsnUPBF+VEoMEcKQh1jKniXsP/BeSASWfbHy76Wm82E6bixbVQJ1JpCOnVO0S5SfIQRMn1FgjSNLL2BgYhBMem3kE2rs7YGObR/gH4aK/6e1mKK/AL0idqSGA/h/WbqnAwnY5DoXQyzVlvJT4P3OBat77CH+ktyw4pckSU2DWaanw4Ae4w4vbrXsnRtWb05utcO1b+YdbXjcnQZ92UmgkJ7Hof6YrvPoUGql523+eJ4FTXDq7hc2Dp+NBuha//i3kzfJKdvzNH5mZoduSrydak1ION4oVu65BapA8r7jmDshA8fPCVlVCC37yKPqiOskw6zXBDc0jFiTV/I7zZL/5ofcJr1fjedYk95cp+5+JrAr4gGKzdh7EPA7RuY9cBtDZf9zMohcaMgFMSkkk5TZQ2UtXGs/3bbjp40jf/NDJYyqBkS2JGJgEVHPxIrhRYJsBzrAqfCXOinLhDIULP+ww2PS/TBiQpZgc5d+Sbshgf8N25Rwjb0oTqVoEypKzpyhIpIQaEQt8a0AUYbkPc7dsflH0zPCdPGiTpU91baESpQRyXawfGfJZn0xNdxYtxyl1ZJa58a4esLv8n+HKM+N39d5OejettJKR6Zyxs6J5RRCtCsznm8rY9mMtGv948Xa18pAs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
