appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ZNqKb4AummCcaIFLRnvfSgirdV5eWk27j7KugxmwXUUmq5Sm15TdWT3JbT3Okvi902FS+i+4N10RSVPMQiJ2q0N6JSHdZfzJDkpG74aXF6XIo4Z/HRb1+qq4SJoC6c5RJCyKvdxcQPPs5H3qSr8RCDFdGFjKKoMahKRZTU/ZL99mx2TijsNcujTUG0yTEz6fh0UbJRNaAl7/P75ZFWx9prc/YHBfowqmP8nMZFrjAYHCtkoBQnNz9lHCVp9FFYa8WSxio512HN6hBC2b5zpaQX+OzREsq4wvU00J/MERlSjACg6qjMda9Bw/sRVzWGtK3i9gp6mPZH6Q/1unegqoZN8QrD77CkRVLAYwcFJJOY+MYmWrR71aXxmo+4Qb+v50S5mdrWuX+GO9o7xyoKsrmyHoyAxhZ5u0PwS5EQeCCc4D/rRlQeOhMKz34E77atsmYkwqJgPE6+HUiwVRWMlDbIZLjJEeMIHziON3xi/tUXqn5wXqYYmR7GkNXirc7ulorx5XN1nQHiaTdv7V90XYGTf1FpnjzdtHcHQJI+ZrHSbkb5+PDCHF2kg45Hmjs/bW2hmdtEoJsFUUCGH+aevTetqflgWh0dDjzu1v+9f/j/jnosp5ZjERf11Se6AEIdn6LPMz6yKIwypzPaoflXsF9muDthHNEtSVyF+Vmogvams=
